# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


User.create(username: "Guest", password: "password")


Manga.create(title:"Ruroni Kenshin (るろうに剣心) Vol.1", author:"Nobuhiro Watsuki",  synopsis:"During the Meiji 11th (1878), a peaceful wanderer called Himura Kenshin, formerly known as the Hitokiri Battōsai, arrives in Tokyo, where he meets Kamiya Kaoru whose swordsmanship school is in danger as a murderer from the city claims to be from that school. After investigating, Kenshin defeats the murderer using his sakabatō sword, which has a reversed blade, making it almost impossible to kill someone. When Kenshin decides to leave Tokyo, Kaoru offers him a place to live in her dojo. During his stay in the dojo, Kenshin rescues an orphan called Myōjin Yahiko from a group of yakuza and takes him to live and train in the dojo. A few days later, a fight merchant named Sagara Sanosuke is hired to attack Kenshin. The volume ends with a one-shot by Watsuki called Rurouni Meiji Swordsman Romantic Story.", img_url: "http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478411730/manga%20covers/kenshin_vol1.jpg")
Manga.create(title:"Ruroni Kenshin (るろうに剣心) Vol.2", author:"Nobuhiro Watsuki",  synopsis:"When the chief of the Police Sword Corps himself comes asking for favors, things must be bad. Hitokiri Udô Jin-e--a black-hatted, crazy-eyed slayer who fells both targets and innocent bystanders alike--is steadily working his way through a list of former Ishin Shishi patriots now ensconced within position of power in the Meiji government. Can Kenshin withstand the hypnotic, paralyzing effect of Jin-e...? ", img_url: "http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478548454/manga%20covers/kenshin2.jpg" )
Manga.create(title:"Ruroni Kenshin (るろうに剣心) Vol.3", author:"Nobuhiro Watsuki",  synopsis:"Spider's Web...like ordinary opium, but better processed. Half the cost to produce, but twice the profits! To the people of Aizu, Takani Megumi was a daughter in a famous family of doctors, in which everyone--women and children alike--studied medicine. But to grasping industrialist Takeda Kanryû, she is the hen who lays the golden egg--the only one who knows the Spider\'s Web formula! To stay with Kanryû is to send even more to their deaths. But to stay with Kenshin and the others is to invite theirs...", img_url: "http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478548454/manga%20covers/kenshin3.jpg")
Manga.create(title:"Ruroni Kenshin (るろうに剣心) Vol.4", author:"Nobuhiro Watsuki",  synopsis:"Shinomori Aoshi was once the leader of Edo Castle's elite guard, the Oniwabanshû. But with the fighting at an end and the shôgunate overthrown, the brilliant Aoshi and his four most loyal onmitsu, or spies, find themselves without a home or a purpose. When fighting is your life, loyalty to those lost ideals (and to the man who most symbolized them) may be the one thing left. But Megumi's life is at stake, and however sympathetic Kenshin may feel, he will fight on, to the last man if necessary...", img_url: "http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478548454/manga%20covers/kenshin4.jpg")
Manga.create(title:"Ruroni Kenshin (るろうに剣心) Vol.5", author:"Nobuhiro Watsuki",  synopsis:"Isurugi Raijûta, a truly old-school swordsman, comes to Kenshin and requests his aid in reforming the state of swordsmanship schools, or kenjutsu dojo, in Japan. Although Kenshin is intrigued by Raijûta's ideals (chiefly, that there is a need for a nation-wide, unifying school), Raijûta's plan to weed out the schools he deems unfit is not in accordance with Kenshin's deepest-held beliefs. Given the choice of either joining Raijûta's Shinko-ryû movement or dying, Kenshin walks away, choosing neither. But Raijûta isn't willing to let Kenshin off the hook so easily...", img_url: "http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478548454/manga%20covers/kenshin_5.jpg")
Manga.create(title:"Ruroni Kenshin (るろうに剣心) Vol.6", author:"Nobuhiro Watsuki",  synopsis:"Kenshin's battle with Raijûta to decide the fate of Meiji Era swordsmanship is coming to a head. One fact is quickly becoming apparent: Raijûta will stop at nothing to ensure the supremacy of his own school of sword-fighting! Reunited with a member of the former Sekihô Army--that doomed civilian unit--Sanosuke runs into trouble of his own. Old alliances are challenged when a plan to topple the current government by any means necessary is shared...and as his friend puts it, Sano's either in, or in the way. Plus a bonus installment containing the first story Nobuhiro Watsuki ever published!", img_url: "http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478548454/manga%20covers/kenshin_6.jpg")
Manga.create(title:"Ruroni Kenshin (るろうに剣心) Vol.7", author:"Nobuhiro Watsuki",  synopsis:"The Shinsengumi--fearsome and formidable protectors of the Shôgunate. Kenshin knows them well, having done battle with them during the final days of the Meiji Restoration. One man in particular--Saitô Hajime, captain of the third unit--lingers in Kenshin's mind. Now an officer of the law and known as Fujita Gorô, Saitô arrives on the steps of the Kamiya Dojo, challenging Kenshin to a duel that will force a reawakening of Kenshin's own past. But the confrontation with Saitô is just the beginning of something much larger, something that will involve the future of the new Japan... ", img_url: "http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478548454/manga%20covers/kenshin_7.jpg")
Manga.create(title:"Dragon Ball, Vol. 1: The Monkey King", author:"Akira Toyama", synopsis:"Before there was Dragon Ball Z , there was Akira Toriyama's action epic Dragon Ball , starring the younger version of Son Goku and all the other Dragon Ball Z heroes! Meet a naive young monkey-tailed boy named Goku, whose quiet life changes when he meets Bulma, a girl who is on a quest to collect seven Dragon Balls. If she gathers them all, an incredibly powerful dragon will appear and grant her one wish. But the precious orbs are scattered all over the world, and Bulma needs Goku's help (and his super-strength)! With a magic staff for a weapon and a flying cloud for a ride, Goku sets out on the adventure of a lifetime...",published: "September 10th 1985", img_url:"")
Manga.create(title:"Dragon Ball, Vol. 2: Wish Upon a Dragon", author:"Akria Toyama", synopsis:"With the (reluctant) help of the shapeshifting pig Oolong, Goku and Bulma have found almost all the Dragon Balls they need to get their wish! To get the sixth Dragon Ball, the fearsome Ox King sends Goku on a mission: to find Kame-Sen'nin, the Turtle Hermit, whose mighty powers can put out the raging fires of Fry-Pan Mountain! But the sleazy old martial artist might just make it more trouble than it's worth! Then, with the bandits Yamcha and Pu'ar on their trail, our heroes continue their quest for the seventh and final Dragon Ball. But can they get it from little Emperor Pilaf, who wants to use his wish to rule the world?!!", published: "January 10th 1986", img_url:"")
Manga.create(title:"Dragon Ball, Vol. 3: The Training of Kame-Sen'nin ", author:"Akria Toyama", synopsis:"", published: "June 10th 1986",img_url:"")
Manga.create(title:"", author:"Akria Toyama", synopsis:"", published: "September 10th 1985", img_url:"")
Manga.create(title:"", author:"Akria Toyama", synopsis:"", published: "September 10th 1985", img_url:"")
Manga.create(title:"", author:"Akria Toyama", synopsis:"", published: "September 10th 1985", img_url:"")
Manga.create(title:"", author:"Akria Toyama", synopsis:"", published: "September 10th 1985", img_url:"")
Manga.create(title:"", author:"Akria Toyama", synopsis:"", published: "September 10th 1985", img_url:"")
Manga.create(title:"", author:"Akria Toyama", synopsis:"", published: "September 10th 1985", img_url:"")
Manga.create(title:"", author:"Akria Toyama", synopsis:"", published: "September 10th 1985", img_url:"")
