# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


User.create(username: "Guest", password: "password", email: "guest@mangareads.com")
Bookshelf.create({user_id: 1, title: "Want-To-Read"})
Bookshelf.create({user_id: 1, title: "Read"})
Bookshelf.create({user_id: 1, title: "Currently-Reading"})




Manga.create(title:"Dragon Ball, Vol. 7: General Blue and the Pirate Treasure", author:"Akira Toyama", synopsis:"Only Goku, Bulma and Kuririn stand between the Red Ribbon Army and the seven Dragon Balls which can grant any wish in the world! Using a submarine loaned by Kame-Sen'nin, the heroic trio explores a pirate's undersea cave in search of the next Dragon Ball , but gun-toting bad guys are on their tail! Now they must face not only perilous pirate traps but the sinister General Blue, a martial artist with powers even Goku doesn't have! Can they escape the cave alive? As the battle continues, Goku and General Blue go to Penguin Village, the home of the weird scientist Dr. Slump and one of the strangest places on Earth!", img_url:"http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478899770/manga%20covers/dragonball7.jpg")
Manga.create(title:"Ruroni Kenshin (るろうに剣心) Vol.2", author:"Nobuhiro Watsuki",  synopsis:"When the chief of the Police Sword Corps himself comes asking for favors, things must be bad. Hitokiri Udô Jin-e--a black-hatted, crazy-eyed slayer who fells both targets and innocent bystanders alike--is steadily working his way through a list of former Ishin Shishi patriots now ensconced within position of power in the Meiji government. Can Kenshin withstand the hypnotic, paralyzing effect of Jin-e...? ", img_url: "http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478548454/manga%20covers/kenshin2.jpg")
Manga.create(title:"Azumanga Daioh Vol. 3", author:"Kiyohiko Azuma", synopsis:"The girls enter their senior year and Miss Yukari speaks ill of Tomo in the third volume of Azumanga Daioh! This volume marks the return of the sports meet, where Sakaki, Osaka, Kagura and the others compete in categories like the three-legged race and beanbag tossing, while Chiyo-chan races to find an idiot for the scavenger hunt... The manga also includes a First Dream of the New Year special, where Sakaki meets Chiyo-chan's tomato-hating father and his penguin housekeeper... Will Osaka succeed in her resolution to get faster? Will Kaorin ever let go of Sakaki? Find out in Azumanga Daioh volume 3!", img_url:"http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478901217/manga%20covers/azu3.jpg")
Manga.create(title:"Ruroni Kenshin (るろうに剣心) Vol.4", author:"Nobuhiro Watsuki",  synopsis:"Shinomori Aoshi was once the leader of Edo Castle's elite guard, the Oniwabanshû. But with the fighting at an end and the shôgunate overthrown, the brilliant Aoshi and his four most loyal onmitsu, or spies, find themselves without a home or a purpose. When fighting is your life, loyalty to those lost ideals (and to the man who most symbolized them) may be the one thing left. But Megumi's life is at stake, and however sympathetic Kenshin may feel, he will fight on, to the last man if necessary...", img_url: "http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478548454/manga%20covers/kenshin4.jpg")
Manga.create(title:"Ruroni Kenshin (るろうに剣心) Vol.5", author:"Nobuhiro Watsuki",  synopsis:"Isurugi Raijûta, a truly old-school swordsman, comes to Kenshin and requests his aid in reforming the state of swordsmanship schools, or kenjutsu dojo, in Japan. Although Kenshin is intrigued by Raijûta's ideals (chiefly, that there is a need for a nation-wide, unifying school), Raijûta's plan to weed out the schools he deems unfit is not in accordance with Kenshin's deepest-held beliefs. Given the choice of either joining Raijûta's Shinko-ryû movement or dying, Kenshin walks away, choosing neither. But Raijûta isn't willing to let Kenshin off the hook so easily...", img_url: "http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478548454/manga%20covers/kenshin_5.jpg")
Manga.create(title:"Ruroni Kenshin (るろうに剣心) Vol.7", author:"Nobuhiro Watsuki",  synopsis:"The Shinsengumi--fearsome and formidable protectors of the Shôgunate. Kenshin knows them well, having done battle with them during the final days of the Meiji Restoration. One man in particular--Saitô Hajime, captain of the third unit--lingers in Kenshin's mind. Now an officer of the law and known as Fujita Gorô, Saitô arrives on the steps of the Kamiya Dojo, challenging Kenshin to a duel that will force a reawakening of Kenshin's own past. But the confrontation with Saitô is just the beginning of something much larger, something that will involve the future of the new Japan... ", img_url: "http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478548454/manga%20covers/kenshin_7.jpg")
Manga.create(title:"Dragon Ball, Vol. 1: The Monkey King", author:"Akira Toyama", synopsis:"Before there was Dragon Ball Z , there was Akira Toriyama's action epic Dragon Ball , starring the younger version of Son Goku and all the other Dragon Ball Z heroes! Meet a naive young monkey-tailed boy named Goku, whose quiet life changes when he meets Bulma, a girl who is on a quest to collect seven Dragon Balls. If she gathers them all, an incredibly powerful dragon will appear and grant her one wish. But the precious orbs are scattered all over the world, and Bulma needs Goku's help (and his super-strength)! With a magic staff for a weapon and a flying cloud for a ride, Goku sets out on the adventure of a lifetime...", img_url:"http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478851476/manga%20covers/dragonball1.jpg")
Manga.create(title:"Dragon Ball, Vol. 5: The Red Ribbon Army", author:"Akira Toyama", synopsis:"In the final round of the Strongest under the Heavens martial arts competition, it's down to Goku vs. Jackie Chun, the mysterious old man who's as powerful as Kame-Sen'nin himself! Will the audience survive the confrontation? After the smoke clears, Goku jumps on his flying cloud and returns to his quest to find the seven Dragon Balls, but now he's not the only one looking for them. The evil Red Ribbon Army wants the Dragon Balls for themselves, and to stop their plans, Goku must go around the world--and survive the six deadly floors of Colonel White's fortress, Muscle Tower!", img_url:"http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478899763/manga%20covers/dragonball5.jpg")
Manga.create(title:"Trigun: Deep Space Planet Future Gun Action!! Vol. 1", author:"Yasuhiro Nightow", synopsis:" Action, comedy, science fiction, and western gunslinger action congregate within these pages. Created by Yasuhiro Nightow, this compound of genre-bending ingredients has turned the Trigun animation into a wildly popular series, and finally, the long-awaited manga comes to America. Somehow the past has placed a sixty billion double dollar bounty on Vash's head, and the gunslinging pacifist can't seem to get away from money grubbing, itchy-trigger-finger citizenry. Find out why Vash is worth so much money dead! Feel the clumsy worry of the unfortunate citizens of the pulverous planet! ", img_url:"http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478901217/manga%20covers/tri_1.jpg")
Manga.create(title:"Dragon Ball, Vol. 6: Bulma Returns!", author:"Akira Toyama", synopsis:"In the frozen north, Goku's one-man fight against the Red Ribbon Army continues as he storms the perilous Muscle Tower! Can he defeat General White's squad of ninjas, cyborgs, and worse, and save the peaceful people of Jingle Village from their oppressors? Then, Goku travels to the City of the West to visit his old friend Bulma, who joins him on his quest, bringing her latest inventions. Their quest for the next Dragon Ball takes them around the world to a jungle island in the South Seas...but to get THIS Dragon Ball they'll have to go through General Blue! ", img_url:"http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478899771/manga%20covers/dragonball6.jpg")
Manga.create(title:"Full Metal Panic! Volume 2", author:"Shouji Gatou,", synopsis:"The students of Jindai High are bound of Okinawa on a field trip, but a hijacking changes their plans! Among the hijackers is Gauron, a mortal enemy Sosuke thought he'd killed years ago. But Gauron is after only one of the students on board...Kaname! The information she carries could be the key to maintaining the balance of power. When they single her out, it's up to Sosuke to save the day again, and a crushing mecha battle for Kaname's freedom ensues. ", img_url:"http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478901218/manga%20covers/fullmetal1.jpg")
Manga.create(title:"Ruroni Kenshin (るろうに剣心) Vol.3", author:"Nobuhiro Watsuki",  synopsis:"Spider's Web...like ordinary opium, but better processed. Half the cost to produce, but twice the profits! To the people of Aizu, Takani Megumi was a daughter in a famous family of doctors, in which everyone--women and children alike--studied medicine. But to grasping industrialist Takeda Kanryû, she is the hen who lays the golden egg--the only one who knows the Spider\'s Web formula! To stay with Kanryû is to send even more to their deaths. But to stay with Kenshin and the others is to invite theirs...", img_url: "http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478548454/manga%20covers/kenshin3.jpg")
Manga.create(title:"Cowboy Bebop, Vol. 1", author:"Yutaka Nanten", synopsis:"From one of the most popular anime series of all time comes a manga to match. Spinning off from the anime story line seen on Cartoon Network, the manga series hooks readers with the same combination of Sci Fi action, crazy comedy, and a twist of old-school hipster cool. This black-and-white miniseries, released in the 100% Authentic Manga format, is perfect for fans of the Cowboy Bebop anime.", img_url:"http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478900237/manga%20covers/bebop1.jpg")
Manga.create(title:"Cowboy Bebop: Shooting Star, Volume 2", author:"Cain Kuga, Hajime Yatate", synopsis:"Cowboy Bebop: Shooting Star is an alternate telling of the famous television show that contains all the same intrigue, adventure, action and gritty noir ambience of its small screen counterpart. A fantastic yarn in its own right, this two-volume series is a perfect addition to any Cowboy Bebop collection.", img_url:"http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478900237/manga%20covers/bebop2.jpg")
Manga.create(title:"Trigun Maximum Volume 3: His Life As A ...", author:"Yasuhiro Nightow", synopsis:"Trigun Maximum Volume 3 is intensity embodied — a front to back fight! Vash the Stampede and the mysterious Wolfwood versus the terribly resilient Gray the Ninelives and one of Yasuhiro Nightow's most curious villains, the completely frightening puppet master, Leonoff. The Gung-Ho Guns get harder and harder to beat as the philosophical tension between our two heroes grows daily.", img_url:"http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478901216/manga%20covers/tri3.jpg")
Manga.create(title:"Dragon Ball, Vol. 3: The Training of Kame-Sen'nin", author:"Akira Toyama", synopsis:"With the Dragon Balls gone and Bulma's summer vacation over, Goku goes to the remote house of the Turtle Hermit, Kame-Sen'nin, to be trained in the martial arts. There, the girl-ogling old master promises to teach Goku everything he knows...and prepare him for the Tenka'ichi Budôkai, the great tournament to determine the Strongest Fighter in the World! But Goku's fellow student, the Shaolin monk Kuririn, isn't above cheating to be the best. Can the two of them get along as they undergo the strangest martial arts training ever?", img_url:"http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478899652/manga%20covers/dragonball3.jpg")
Manga.create(title:"Cowboy Bebop, Vol. 2", author:"Yutaka Nanten", synopsis:"The hippest bounty hunters in the galaxy are back! Spike Siegel Jet Black and Faye Valentine are on the hunt for new targets inspired by the hit anime series. Cowboy Bebop blends science fiction spaghetti westerns film noir and jazz music into a new genre that s all about style.", img_url:"http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478900237/manga%20covers/bebop3.jpg")
Manga.create(title:"Dragon Ball, Vol. 4: Strongest Under the Heavens ", author:"Akira Toyama", synopsis:"Goku has made it to the Tenka'ichi Budôkai, the world's #1 martial arts tournament...but even the training of the martial arts master Kame-Sen'nin hasn't prepared him for this! Only seven finalists remain. Will the champion be Goku? His fellow student Kuririn? Yamcha, master of the Fist of the Wolf Fang? Fighting woman Ran Fuan? Giran, a rubbery monster who's part dinasaur? Namu, an Indian mystic? Or Jackie Chun, the mysterious old man who may be the toughest fighter of all? There can be only one winner in the wildest, craziest battle ever!", img_url:"http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478899757/manga%20covers/dragonball4.jpg")
Manga.create(title:"Azumanga Daioh Vol. 1", author:"Kiyohiko Azuma", synopsis:"It's tough to tell the difference between teacher and students in Azuma's comedy. Teacher Yukari Tanizaki is oblivious, immature, emotional and one of the people shaping young minds. Her students face difficulties in school that most never imagined. For example, as one pupil starts to ask a question, Miss Yukari cuts him off, stating she won't talk about her bra size. Another group of students are ready for their lessons, but instead of learning about social studies or science, they learn how Miss Yukari spent her weekend. Maybe that's not so bad, considering Miss Yukari's not the brightest bulb in the bunch and has her students correcting her on many technical points. Her students aren't sure how to react, but their bewilderment is half the charm of this manga. Like the 1980s TV series Head of the Class, Azu has an eclectic mix of pupils ranging from child geniuses to sports enthusiasts to tough girls; each possessing much more than meets the eye. The precocious child genius may be great at academic subjects, but she still draws like a little girl and has the emotions of a kid. The unemotional tough teen melts for tiny animals and longs to have a pet of her own, even if all of the creatures she comes in contact with seem to hate her. The art is simple and minimalistic, but adequately conveys the thought and emotion behind each strip. Azuma's cast has depth, dimension and character, and their story heartily entertains.", img_url:"http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478901217/manga%20covers/azu1.jpg")
Manga.create(title:"Azumanga Daioh Vol. 2", author:"Kiyohiko Azuma", synopsis:"It's not manga, it's Azumanga (and it's smart, fun and totally addictive)! Created by the iconoclastic Kiyohiko Azuma (hence the name), Azumanga Daioh is strongly character driven, telling the story of a group of high-school girls and their hilarious daily tribulations.", img_url:"http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478901217/manga%20covers/azu2.jpg")
Manga.create(title:"Ruroni Kenshin (るろうに剣心) Vol.1", author:"Nobuhiro Watsuki",  synopsis:"During the Meiji 11th (1878), a peaceful wanderer called Himura Kenshin, formerly known as the Hitokiri Battōsai, arrives in Tokyo, where he meets Kamiya Kaoru whose swordsmanship school is in danger as a murderer from the city claims to be from that school. After investigating, Kenshin defeats the murderer using his sakabatō sword, which has a reversed blade, making it almost impossible to kill someone. When Kenshin decides to leave Tokyo, Kaoru offers him a place to live in her dojo. During his stay in the dojo, Kenshin rescues an orphan called Myōjin Yahiko from a group of yakuza and takes him to live and train in the dojo. A few days later, a fight merchant named Sagara Sanosuke is hired to attack Kenshin. The volume ends with a one-shot by Watsuki called Rurouni Meiji Swordsman Romantic Story.", img_url: "http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478411730/manga%20covers/kenshin_vol1.jpg")
Manga.create(title:"Ruroni Kenshin (るろうに剣心) Vol.6", author:"Nobuhiro Watsuki",  synopsis:"Kenshin's battle with Raijûta to decide the fate of Meiji Era swordsmanship is coming to a head. One fact is quickly becoming apparent: Raijûta will stop at nothing to ensure the supremacy of his own school of sword-fighting! Reunited with a member of the former Sekihô Army--that doomed civilian unit--Sanosuke runs into trouble of his own. Old alliances are challenged when a plan to topple the current government by any means necessary is shared...and as his friend puts it, Sano's either in, or in the way. Plus a bonus installment containing the first story Nobuhiro Watsuki ever published!", img_url: "http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478548454/manga%20covers/kenshin_6.jpg")
Manga.create(title:"Dragon Ball, Vol. 2: Wish upon a Dragon", author:"Akira Toyama", synopsis:"Dragon Ball introduces a young monkey-tailed boy named Goku (a wry update of the classic Chinese Monkey King legend), whose quiet life changes when he meets a girl named Bulma who is on a quest to collect seven Dragon Balls. If she gathers them all, an incredibly powerful dragon will appear and grant her one wish. But the precious orbs are scattered all over the world, and Bulma could use the help of a certain super-strong boy... (In Japan, Dragon Ball and Dragon Ball Z were originally a single 42-volume series. VIZ Media's Dragon Ball contains vols. 1-16 of the original Japanese Dragon Ball , from the beginning of the series to the climax of Goku's last fight with Piccolo.)", img_url:"http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478851605/manga%20covers/dragonball2.jpg")
Manga.create(title:"Azumanga Daioh Vol. 4", author:"Kiyohiko Azuma", synopsis:"The gang of high schoolers takes a trip to sunny Okinawa, where Osaka plays with sea cucumbers. Yomi announces her intention to join InterPol, and Sakaki gets a cat that will let her pet it. When the gang gets together for a camping trip, Mr. Kimura makes his big confession to one of the students. This volume is a part of the popular series.", img_url:"http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478901216/manga%20covers/azu4.jpg")
Manga.create(title:"Trigun: Deep Space Planet Future Gun Action!! Vol. 2", author:"Yasuhiro Nightow", synopsis:"There's a mysterious past buried in the mind of the affable, yet somehow incredibly dangerous Vash the Stampede, and everyone on this desert planet seems to know about it. Not only that, they've been trying to hunt him down for the sixty million double-dollar bounty on his head. Well, enter two insurance adjuster ladies, claiming that the man is a localized disaster, and voila! No more bounty. But that doesn't seem to end Vash's troubles, or his trail of destruction.", img_url:"http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478901216/manga%20covers/tri2.jpg")
Manga.create(title:"R.O.D. Read or Die 3", author:"Hideyuki Kurata, Hideyuki Kurata, Shutaro Yamada", synopsis:"Yomiko Readman's love for literature goes far beyond any run-of-the-mill bookworm's! In fact, she has a supernatural ability to manipulate paper in the most amazing ways. From turning a tiny scrap into a lethal throwing dagger to making a single sheet hard enough to block bullets, she's only limited by her imagination. She uses her phenomenal power to seek out legendary books containing secret information that in the wrong hands could be dangerous. Backed by a Special Operations Division in England, Yomiko has her hands full battling evildoers, saving the world, and trying to find time to curl up with a good book.", img_url:"http://res.cloudinary.com/ddbfkqb9m/image/upload/v1478901216/manga%20covers/rod1.jpg")
